general{
	layout = master
	allow_tearing = true

}

misc{
	force_default_wallpaper = 0
	disable_hyprland_logo = true
}

master{
	new_status = slave
	orientation = left
	mfact = 0.62
	allow_small_split = true
	
}
input{
	kb_layout = us, cz
	kb_variant = ,qwerty
	kb_options = grp:alt_shift_toggle
	touchdevice{
		enabled = false
	}
	touchpad{
	scroll_factor = 0.8
	}
}
