# variables
$mainMod = SUPER # default modifier being "Windowshit" key
$terminal = kitty
$browser = firefox
$menu = wofi --show drun
$max_volume = 3
$code = code
$fileManager = yazi

# launch apps
bind = $mainMod, T, exec, $terminal
bind = $mainMod, Q, killactive
bind = $mainMod, W, exec, $browser
bind = $mainMod, M, exec, $menu
bind = $mainMod, R, exec, hyprctl reload
bind = $mainMod, R, exec, killall waybar && waybar &
bind = $mainMod, C, exec, $code
bind = $mainMod, F, exec, $terminal -e $fileManager
#bind = $mainMod, F, exec, $fileManager #if manager is standalone

# gestures
gesture = 4, horizontal, workspace

# windows
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bind = $mainMod ALT, SPACE, togglefloating
bind = $mainMod, SPACE, fullscreen

# laptop settings
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l $max_volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# workspaces switching
bindl = $mainMod ALT, 1, movetoworkspacesilent, 1
bindl = $mainMod ALT, 2, movetoworkspacesilent, 2
bindl = $mainMod ALT, 3, movetoworkspacesilent, 3
bindl = $mainMod ALT, 4, movetoworkspacesilent, 4
bindl = $mainMod ALT, 5, movetoworkspacesilent, 5
bindl = $mainMod ALT, 6, movetoworkspacesilent, 6
bindl = $mainMod ALT, 7, movetoworkspacesilent, 7
bindl = $mainMod ALT, 8, movetoworkspacesilent, 8
bindl = $mainMod ALT, 9, movetoworkspacesilent, 9
bindl = $mainMod ALT, 0, movetoworkspacesilent, 10

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10
